name: PKDV Group
favicon: null
layout_spectrum: 0.09624121990054846
typography_spectrum: 0.25333701237104833
title: Global. Business. Advisory
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.501754810102284
  lightness: 0.7080380462575704
  saturation: 0.7940118601545691
  rhythmicContrast: 0.12923029554076493
purpose: []
