name: PKDV.IO
favicon: null
layout_spectrum: 0.73202
typography_spectrum: 0.75764
title: PKDV Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#143a65'
    - '#ffffff'
    - '#c7c8d5'
    - '#a1a4b6'
    - '#6e809a'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
