name: Global. Business. Advisory.
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75764
title: PKDV Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cecbc6'
    - '#2a4e8c'
    - '#9b9ea5'
    - '#627ea5'
    - '#746f65'
  brandStrength: 0.875
  lightness: 0.7080380462575704
  saturation: 0.7940118601545691
  rhythmicContrast: 0.12923029554076493
purpose: []
