name: PKDV.IO
favicon: null
layout_spectrum: 0.73202
typography_spectrum: 0.75764
title: Excellence in everything
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6f809b'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
